### ISSUE TITLE
Button Shadow

### ISSUE THREAD

**Issue by DanishAmjad12** [uin3566/AllAngleExpandableButton#2]
Can we a property for button shadow in style. Right now its showing continuously shadow over main button or whenever we click a button a black background is shown. 
Here is the screenshot.

![screenshot_20161003-180149](https://cloud.githubusercontent.com/assets/18696978/19038480/1d5fe28a-8995-11e6-8981-1dc762c45a1b.png)

**Comment by uin3566** [comment]
I'm sorry that I can not understand what you mean clearly.if you can speak chinese,can you express again in  chinese.
by the way,when touch a button,the button color become darker,this is the press effect,it's nothing to do with button shadow.
aebButtonElevation property is used for draw the button shadow,if aebButtonElevation equals 0,it will not draw shadow.

**Comment by DanishAmjad12** [comment]
我的问题是，当你触摸按钮的显示您设置为黑色，你可以在截图中看到的背景阴影颜色。你可以有按钮阴影属性

**Comment by uin3566** [comment]
恩，倒是可以加个阴影颜色属性。

**Comment by DanishAmjad12** [comment]
如何更改按钮阴影颜色？

**Comment by uin3566** [comment]
BUTTON_SHADOW_COLOR和BUTTON_SHADOW_ALPHA这两个常量你可以调来看下，我想了下，按钮颜色如果各不相同，定义非黑色的阴影也挺奇怪，有这种需求的人也挺少的，加个属性貌似也没那个必要，你若是想改变阴影颜色，看着源代码改下就好了。

**Comment by DanishAmjad12** [comment]
ok..
