### ISSUE TITLE
Is it possible to have an icon button with text underneath it?

### ISSUE THREAD

**Issue by stoddayy** [uin3566/AllAngleExpandableButton#5]
Kind of like myfitnesspal:
![img_0127](https://cloud.githubusercontent.com/assets/10616245/23701131/5540408c-03ed-11e7-8a77-22de6307872d.png)

**Comment by uin3566** [comment]
Of course it is possible, but i have not implemented this function in this project. you may do it by yourself

**Comment by ISsAhlel** [comment]
> Of course it is possible, but i have not implemented this function in this project. you may do it by yourself

did you find solution
