### ISSUE TITLE
ExpandMoveCoordinate为空

### ISSUE THREAD

**Issue by hrygddv** [uin3566/AllAngleExpandableButton#6]
```
Attempt to read from field 'float com.fangxu.allangleexpandablebutton.AllAngleExpandableButton$MaskView$ExpandMoveCoordinate.moveX' on a null object reference
```

你好，我有用你的AllAngleExpandableButton，感谢你的付出，但是我遇到了这个问题，请问是怎么导致的呢？代码片段如下:
```Java
if(this.allAngleExpandableButton.expanded) {
                    AllAngleExpandableButton.MaskView.ExpandMoveCoordinate radius = (AllAngleExpandableButton.MaskView.ExpandMoveCoordinate)this.expandDesCoordinateMap.get(buttonData);
                    moveX = this.allAngleExpandableButton.expandProgress * radius.moveX;
                    moveY = this.allAngleExpandableButton.expandProgress * -radius.moveY;
                    matrix.postTranslate(moveX, moveY);
                }
```

另外，如果界面已经渲染了AllAngleExpandableButton，那要怎样改他的visibility呢？（我试过更改，可是好像因为动画的原因会无效）

**Comment by uin3566** [comment]
1、你可以打log看下expandDesCoordinateMap的put跟get的过程，把buttonData地址打出来，这个空指针肯定是expandDesCoordinateMap没获取对应的buttonData，不知道你set这些buttonData之后有没有改变这些buttonData对象，如果有的话那肯定get不到了。
2、关于visibility，如果button已经展开了，这个时候MaskView是可见的，你可以在AllAngleExpandableButton再定义一个方法setVisibility，当设置为INVISIBLE的时候你需要根据expanded状态来更新MaskView的可见状态。

**Comment by Lemniscate317** [comment]
我也试过有这样的异常。场景如下：在button展开的情况下按home键导致activity重启。然后button会变为null，点回去就会出现上面的异常。

**Comment by CamiYe** [comment]
我也遇到了相同的issue，发现了一个问题，那就是我觉得下面这段if里的代码完全可以不用执行，直接执行else里的代码就可以了，正因为这个if判断当expanded的值变为true的时候，而expandDesCoordinateMap中的item在初始化的时候没有被正常赋值就会出现这个issue，这其实是个异步导致的issue。
 if (allAngleExpandableButton.expanded) {
                    ExpandMoveCoordinate coordinate = expandDesCoordinateMap.get(buttonData);
                    float dx = allAngleExpandableButton.expandProgress * (coordinate.moveX);
                    float dy = allAngleExpandableButton.expandProgress * (-coordinate.moveY);
                    matrix.postTranslate(dx, dy);
      } else{
      ......
}
不知道我的解答对不对，望指正！
